-- Crust Extractor
local crust = atom.util.Recipe("crust_extractor")
crust.removeIngredient("steel-plate")
crust.removeIngredient("pipe")
crust.removeIngredient("speed-module")
crust.removeIngredient("engine-unit")
crust.addIngredient("fi_materials_upgrade", 1)
crust.addIngredient("area-mining-drill", 1)
crust.addIngredient("elite-gearbox", 5)
crust.addIngredient("se-dynamic-emitter", 5)
crust.addIngredient("industrial-drill-head", 10)
crust.addIngredient("speed-module-4", 20)
crust.addIngredient("se-heavy-composite", 50)
crust.addIngredient("se-heavy-bearing", 50)
crust.addIngredient("se-space-pipe", 100)

-- Moho Extractor
local moho = atom.util.Recipe("moho_extractor")
moho.removeIngredient("steel-plate")
moho.removeIngredient("pipe")
moho.removeIngredient("speed-module-2")
moho.removeIngredient("electric-engine-unit")
moho.addIngredient("fu_materials_upgrade", 1)
moho.addIngredient("se-heavy-assembly", 10)
moho.addIngredient("se-dynamic-emitter", 10)
moho.addIngredient("industrial-drill-head", 20)
moho.addIngredient("speed-module-5", 20)
moho.addIngredient("imersium-beam", 100)
moho.addIngredient("se-heavy-bearing", 100)
moho.addIngredient("se-space-pipe", 200)

-- Mantle Extractor
local mantle = atom.util.Recipe("mantle_extractor")
mantle.removeIngredient("steel-plate")
mantle.removeIngredient("pipe")
mantle.removeIngredient("speed-module-3")
mantle.removeIngredient("flying-robot-frame")
mantle.addIngredient("gr_materials_upgrade", 1)
mantle.addIngredient("se-heavy-assembly", 20)
mantle.addIngredient("se-dynamic-emitter", 20)
mantle.addIngredient("industrial-drill-head", 40)
mantle.addIngredient("speed-module-6", 20)
mantle.addIngredient("se-naquium-plate", 100)
mantle.addIngredient("se-heavy-bearing", 200)
mantle.addIngredient("se-space-pipe", 300)