removeRecipesByPattern("^enriched%-%a+$")
removeRecipesByPattern("^enriched%-%a+%-plate$")
removeRecipesByPattern("^%a+%-ingot%-to%-plate$")
removeRecipeByName("tantalite-smelting")
removeRecipeByName("tantalite-ingot")
removeRecipeByName("molten-tantalite")