atom.util.recipe.removeByNamePattern("^enriched%-%a+$")
atom.util.recipe.removeByNamePattern("^enriched%-%a+%-plate$")
atom.util.recipe.removeByNamePattern("^%a+%-ingot%-to%-plate$")
atom.util.recipe.removeByName("tantalite-smelting")
atom.util.recipe.removeByName("tantalite-ingot")
atom.util.recipe.removeByName("chromium-plate")
atom.util.recipe.removeByName("molten-cobalt")
atom.util.recipe.removeByName("cobalt-plate")

atom.util.item.removeByName("fi-arc-pure-chrome")
atom.util.item.removeByName("fi-arc-pure-cobalt")
atom.util.item.removeByName("fi-arc-pure-indium")
atom.util.item.removeByName("fi-arc-pure-niobium")
atom.util.item.removeByName("fi-arc-pure-tantalum")