data:extend({
    -- Items
    {
        type = "item",
        name = "fusion-stable-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-stable-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "fusion-speed-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-speed-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "fusion-accuracy-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-accuracy-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "laser-heating-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/laser-heating-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "laser-calculation-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/laser-calculation-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "laser-decay-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/laser-decay-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "magnet-stabilazer-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/magnet-stabilazer-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "magnet-trajectory-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/magnet-trajectory-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "magnet-contain-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/magnet-contain-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },

    {
        type = "item",
        name = "plasma-rotating-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/plasma-rotating-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "plasma-spinning-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/plasma-spinning-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "plasma-star-data",
        icon = "__all-the-overhaul-modpack__/graphics/icons/plasma-star-data.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "highenergy-data-248",
        icon = "__all-the-overhaul-modpack__/graphics/icons/highenergy-data-248.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "radioisotop-data-248",
        icon = "__all-the-overhaul-modpack__/graphics/icons/radioisotop-data-248.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "star-data-248",
        icon = "__all-the-overhaul-modpack__/graphics/icons/star-data-248.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "structural-data-248",
        icon = "__all-the-overhaul-modpack__/graphics/icons/structural-data-248.png",
        icon_size = 64,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "fusion-catalogue-1",
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-1.png",
        icon_size = 128,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "fusion-catalogue-3",
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-3.png",
        icon_size = 128,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "item",
        name = "fusion-catalogue-4",
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-4.png",
        icon_size = 128,
        subgroup = "data-energy",
        order = "f",
        stack_size = 50
    },
    {
        type = "tool",
        name = "fusion-science-pack-1",
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value",
        icon = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-1.png",
        icon_size = 64,
        icon_mipmaps = 1,
        subgroup = "energy-science-pack",
        order = "f",
        stack_size = 200,
        pictures = {
            {
                layers = {
                    {
                        filename = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-1.png",
                        scale = 0.25,
                        size = 64
                    },
                    {
                        filename = "__space-exploration-graphics__/graphics/icons/catalogue/mask-1.png",
                        scale = 0.25,
                        size = 64,
                        draw_as_light = true
                    }
                }
            }
        }
    },
    {
        type = "tool",
        name = "fusion-science-pack-2",
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value",
        icon = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-2.png",
        icon_size = 64,
        icon_mipmaps = 1,
        subgroup = "energy-science-pack",
        order = "f",
        stack_size = 200,
        pictures = {
            {
                layers = {
                    {
                        filename = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-2.png",
                        scale = 0.25,
                        size = 64
                    },
                    {
                        filename = "__space-exploration-graphics__/graphics/icons/catalogue/mask-2.png",
                        scale = 0.25,
                        size = 64,
                        draw_as_light = true
                    }
                }
            }
        }
    },
    {
        type = "tool",
        name = "fusion-science-pack-3",
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value",
        icon = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-3.png",
        icon_size = 64,
        icon_mipmaps = 1,
        subgroup = "energy-science-pack",
        order = "f",
        stack_size = 200,
        pictures = {
            {
                layers = {
                    {
                        filename = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-3.png",
                        scale = 0.25,
                        size = 64
                    },
                    {
                        filename = "__space-exploration-graphics__/graphics/icons/catalogue/mask-3.png",
                        scale = 0.25,
                        size = 64,
                        draw_as_light = true
                    }
                }
            }
        }
    },
    {
        type = "tool",
        name = "fusion-science-pack-4",
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value",
        icon = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-4.png",
        icon_size = 64,
        icon_mipmaps = 1,
        subgroup = "energy-science-pack",
        order = "f",
        stack_size = 200,
        pictures = {
            {
                layers = {
                    {
                        filename = "__all-the-overhaul-modpack__/graphics/icons/all-fusion-science-pack-4.png",
                        scale = 0.25,
                        size = 64
                    },
                    {
                        filename = "__space-exploration-graphics__/graphics/icons/catalogue/mask-4.png",
                        scale = 0.25,
                        size = 64,
                        draw_as_light = true
                    }
                }
            }
        }
    },


    -- Recipes
    {
        type = "recipe",
        name = "fusion-stable-data",
        ingredients = {
            { type = "item", name = "fu_materials_fusion_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-ion-stream", amount = 100 },
        },
        results = {
            { type = "item", name = "fusion-stable-data", amount = 1 },
            { type = "item", name = "se-contaminated-scrap", amount = 8 },
        },
        energy_required = 2,
        main_product = "fusion-stable-data",
        category = "space-collider",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-speed-data",
        ingredients = {
            { type = "item", name = "se-material-testing-pack", amount = 1 },
            { type = "item", name = "kr-dt-fuel-cell", amount = 1 },
            { type = "item", name = "fu_materials_fusion_card", amount = 1 },
            { type = "item", name = "se-atomic-data", amount = 1 },
            { type = "item", name = "se-entanglement-data", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-ion-stream", amount = 100 },
        },
        results = {
            { type = "item", name = "fusion-speed-data", amount = 3 },
            { type = "item", name = "kr-dt-fuel-cell", amount = 1 },
            { type = "item", name = "se-contaminated-scrap", amount = 4 },
        },
        energy_required = 2,
        main_product = "fusion-speed-data",
        category = "space-collider",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-accuracy-data",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "fu_materials_charged_container", amount = 1 },
            { type = "item", name = "fu_materials_fusion_card", amount = 1 },
            { type = "item", name = "se-pressure-containment-data", amount = 1 },
            { type = "item", name = "se-quantum-phenomenon-data", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-ion-stream", amount = 20 },
            { type = "fluid", name = "se-space-coolant-supercooled", amount = 10 },
        },
        results = {
            { type = "item", name = "fusion-accuracy-data", amount_min = 1, amount_max = 3, probability = 0.5 },
            { type = "item", name = "fu_materials_charged_container", amount = 1 },
            { type = "item", name = "se-junk-data", amount_min = 1, amount_max = 1, probability = 0.5 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 1, probability = 0.25 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 4,
        main_product = "fusion-accuracy-data",
        category = "space-collider",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "laser-heating-data",
        ingredients = {
            { type = "item", name = "fu_materials_laser_card", amount = 1 },
            { type = "item", name = "fu_materials_TIM", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-supercooled", amount = 10 },
        },
        results = {
            { type = "item", name = "laser-heating-data", amount = 1 },
            { type = "item", name = "se-contaminated-scrap", amount = 2 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 10,
        main_product = "laser-heating-data",
        category = "space-laser",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "laser-calculation-data",
        ingredients = {
            { type = "item", name = "scanner", amount = 1 },
            { type = "item", name = "se-material-testing-pack", amount = 1 },
            { type = "item", name = "se-explosion-shielding-data", amount = 1 },
            { type = "item", name = "fu_materials_laser_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-supercooled", amount = 10 },
        },
        results = {
            { type = "item", name = "laser-calculation-data", amount = 2 },
            { type = "item", name = "se-contaminated-scrap", amount = 2 },
            { type = "item", name = "scanner", amount_min = 1, amount_max = 1, probability = 0.95 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 5,
        main_product = "laser-calculation-data",
        category = "space-laser",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "laser-decay-data",
        ingredients = {
            { type = "item", name = "spectroscope", amount = 1 },
            { type = "item", name = "se-space-mirror", amount = 2 },
            { type = "item", name = "se-forcefield-data", amount = 1 },
            { type = "item", name = "se-particle-beam-shielding-data", amount = 1 },
            { type = "item", name = "fu_materials_laser_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 2 },
            { type = "fluid", name = "se-space-coolant-supercooled", amount = 10 },
        },
        results = {
            { type = "item", name = "laser-decay-data", amount = 3 },
            { type = "item", name = "se-junk-data", amount = 1 },
            { type = "item", name = "se-scrap", amount = 2 },
            { type = "item", name = "spectroscope", amount_min = 1, amount_max = 1, probability = 0.99 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 3, probability = 0.25 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 5,
        main_product = "laser-decay-data",
        category = "space-laser",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "magnet-stabilazer-data",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "niobium-plate", amount = 1 },
            { type = "item", name = "fu_materials_magnet_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-ion-stream", amount = 50 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "magnet-stabilazer-data", amount_min = 1, amount_max = 1, probability = 0.95 },
            { type = "item", name = "se-junk-data", amount_min = 1, amount_max = 1, probability = 0.04 },
            { type = "item", name = "niobium-plate", amount_min = 1, amount_max = 1, probability = 0.95 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 1, probability = 0.1 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 10,
        main_product = "magnet-stabilazer-data",
        category = "space-electromagnetics",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "magnet-trajectory-data",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "se-electromagnetic-field-data", amount = 1 },
            { type = "item", name = "se-polarisation-data", amount = 1 },
            { type = "item", name = "fu_materials_magnet", amount = 1 },
            { type = "item", name = "fu_materials_magnet_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "magnet-trajectory-data", amount = 3 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 1, probability = 0.25 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 10,
        main_product = "magnet-trajectory-data",
        category = "space-electromagnetics",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "magnet-contain-data",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "se-experimental-alloys-data", amount = 1 },
            { type = "item", name = "se-superconductivity-data", amount = 1 },
            { type = "item", name = "highenergy-data-248", amount = 1 },
            { type = "item", name = "fu_materials_magnet_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-ion-stream", amount = 50 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "magnet-contain-data", amount = 3 },
            { type = "item", name = "se-junk-data", amount_min = 1, amount_max = 1, probability = 0.95 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 1, probability = 0.25 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 10,
        main_product = "magnet-contain-data",
        category = "space-electromagnetics",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "plasma-rotating-data",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "fu_materials_plasma_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-proton-stream", amount = 20 },
            { type = "fluid", name = "se-space-coolant-supercooled", amount = 10 },
        },
        results = {
            { type = "item", name = "plasma-rotating-data", amount_min = 1, amount_max = 1, probability = 0.7 },
            { type = "item", name = "se-junk-data", amount_min = 1, amount_max = 1, probability = 0.29 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 5,
        main_product = "plasma-rotating-data",
        category = "space-collider",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "plasma-spinning-data",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "se-quantum-phenomenon-data", amount = 1 },
            { type = "item", name = "fu_materials_plasma_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-ion-stream", amount = 20 },
            { type = "fluid", name = "se-space-coolant-supercooled", amount = 10 },
        },
        results = {
            { type = "item", name = "plasma-spinning-data", amount_min = 1, amount_max = 2, probability = 0.6 },
            { type = "item", name = "se-junk-data", amount_min = 1, amount_max = 1, probability = 0.39 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 1, probability = 0.25 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 5,
        main_product = "plasma-spinning-data",
        category = "space-collider",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "plasma-star-data",
        ingredients = {
            { type = "item", name = "se-magnetic-canister", amount = 5 },
            { type = "item", name = "se-hot-thermodynamics-data", amount = 1 },
            { type = "item", name = "se-gravitational-lensing-data", amount = 1 },
            { type = "item", name = "se-fusion-test-data", amount = 1 },
            { type = "item", name = "fu_materials_plasma_card", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-particle-stream", amount = 100 },
        },
        results = {
            { type = "item", name = "plasma-star-data", amount_min = 3, amount_max = 3, probability = 0.6 },
            { type = "item", name = "se-junk-data", amount_min = 1, amount_max = 1, probability = 0.39 },
            { type = "item", name = "se-scrap", amount = 15 },
            { type = "item", name = "se-contaminated-scrap", amount = 10 },
        },
        main_product = "plasma-star-data",
        category = "space-materialisation",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "highenergy-data-248",
        ingredients = {
            { type = "item", name = "nickel-electromagnet", amount = 1 },
            { type = "item", name = "fi_energy_crystal_charged_item", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "highenergy-data-248", amount = 1 },
            { type = "item", name = "fi_energy_crystal_charged_item", amount_min = 1, amount_max = 1, probability = 0.99 },
            { type = "item", name = "nickel-electromagnet", amount_min = 1, amount_max = 1, probability = 0.75 },
            { type = "item", name = "se-contaminated-scrap", amount = 1 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 10,
        main_product = "highenergy-data-248",
        category = "space-electromagnetics",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "radioisotop-data-248",
        ingredients = {
            { type = "item", name = "fi_plutonium239_item", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
        },
        results = {
            { type = "item", name = "radioisotop-data-248", amount = 1 },
            { type = "item", name = "fi_plutonium239_item", amount_min = 1, amount_max = 1, probability = 0.99 },
        },
        energy_required = 8,
        main_product = "radioisotop-data-248",
        category = "space-radiation",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "star-data-248",
        ingredients = {
            { type = "item", name = "scanner", amount = 1 },
            { type = "item", name = "se-visible-observation-data", amount = 1 },
            { type = "item", name = "se-uv-observation-data", amount = 1 },
            { type = "item", name = "se-infrared-observation-data", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 1 },
        },
        results = {
            { type = "item", name = "star-data-248", amount = 4 },
            { type = "item", name = "scanner", amount_min = 1, amount_max = 1, probability = 0.99 },
            { type = "item", name = "se-scrap", amount_min = 1, amount_max = 1, probability = 0.1 },
        },
        energy_required = 8,
        main_product = "star-data-248",
        category = "space-astrometrics",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "structural-data-248",
        ingredients = {
            { type = "item", name = "se-material-testing-pack", amount = 3 },
            { type = "item", name = "inconel-718", amount = 1 },
            { type = "item", name = "low-density-structure", amount = 1 },
            { type = "item", name = "aluminum-6061", amount = 1 },
            { type = "item", name = "se-empty-data", amount = 3 },
            { type = "fluid", name = "lubricant", amount = 5 },
        },
        results = {
            { type = "item", name = "structural-data-248", amount = 3 },
            { type = "item", name = "se-scrap", amount = 6 },
            { type = "fluid", name = "se-contaminated-space-water", amount = 1 },
        },
        energy_required = 10,
        main_product = "structural-data-248",
        category = "space-mechanical",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-catalogue-1",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "highenergy-data-248", amount = 1 },
            { type = "item", name = "radioisotop-data-248", amount = 1 },
            { type = "item", name = "star-data-248", amount = 1 },
            { type = "item", name = "structural-data-248", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "fusion-catalogue-1", amount = 1 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 20,
        main_product = "fusion-catalogue-1",
        category = "catalogue-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-catalogue-2",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "fusion-stable-data", amount = 1 },
            { type = "item", name = "laser-heating-data", amount = 1 },
            { type = "item", name = "magnet-stabilazer-data", amount = 1 },
            { type = "item", name = "plasma-rotating-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "fu_tech_sign_item", amount = 1 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 20,
        main_product = "fu_tech_sign_item",
        category = "catalogue-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-catalogue-3",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "fusion-speed-data", amount = 1 },
            { type = "item", name = "laser-calculation-data", amount = 1 },
            { type = "item", name = "magnet-trajectory-data", amount = 1 },
            { type = "item", name = "plasma-spinning-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "fusion-catalogue-3", amount = 1 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 20,
        main_product = "fusion-catalogue-3",
        category = "catalogue-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-catalogue-4",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "fusion-accuracy-data", amount = 1 },
            { type = "item", name = "laser-decay-data", amount = 1 },
            { type = "item", name = "magnet-contain-data", amount = 1 },
            { type = "item", name = "plasma-star-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 10 },
        },
        results = {
            { type = "item", name = "fusion-catalogue-4", amount = 1 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 10 },
        },
        energy_required = 20,
        main_product = "fusion-catalogue-4",
        category = "catalogue-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-science-pack-1",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "fusion-catalogue-1", amount = 1 },
            { type = "item", name = "chromium-plate", amount = 20 },
            { type = "item", name = "se-significant-data", amount = 1 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 20 },
        },
        results = {
            { type = "item", name = "fusion-science-pack-1", amount = 2 },
            { type = "item", name = "se-junk-data", amount = 6 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 20 },
        },
        energy_required = 30,
        main_product = "fusion-science-pack-1",
        category = "science-pack-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-science-pack-2",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "se-significant-data", amount = 1 },
            { type = "item", name = "fu_tech_sign_item", amount = 1 },
            { type = "item", name = "fusion-science-pack-1", amount = 2 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 20 },
        },
        results = {
            { type = "item", name = "fusion-science-pack-2", amount = 4 },
            { type = "item", name = "se-junk-data", amount = 6 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 20 },
        },
        energy_required = 30,
        main_product = "fusion-science-pack-2",
        category = "science-pack-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-science-pack-3",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "se-significant-data", amount = 1 },
            { type = "item", name = "fu_materials_magnet", amount = 1 },
            { type = "item", name = "fusion-catalogue-3", amount = 1 },
            { type = "item", name = "fusion-science-pack-2", amount = 4 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 20 },
        },
        results = {
            { type = "item", name = "fusion-science-pack-3", amount = 6 },
            { type = "item", name = "se-junk-data", amount = 6 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 20 },
        },
        energy_required = 30,
        main_product = "fusion-science-pack-3",
        category = "science-pack-creation-1",
        enabled = false,
        always_show_made_in = true,
    },
    {
        type = "recipe",
        name = "fusion-science-pack-4",
        allow_productivity = true,
        ingredients = {
            { type = "item", name = "se-significant-data", amount = 1 },
            { type = "item", name = "kr-tritium", amount = 1 },
            { type = "item", name = "fusion-catalogue-4", amount = 1 },
            { type = "item", name = "fusion-science-pack-3", amount = 6 },
            { type = "fluid", name = "se-space-coolant-cold", amount = 20 },
        },
        results = {
            { type = "item", name = "fusion-science-pack-4", amount = 8 },
            { type = "item", name = "se-junk-data", amount = 6 },
            { type = "fluid", name = "se-space-coolant-hot", amount = 20 },
        },
        energy_required = 30,
        main_product = "fusion-science-pack-4",
        category = "science-pack-creation-1",
        enabled = false,
        always_show_made_in = true,
    },


    -- Technology
    {
        type = "technology",
        name = "space-fusion-catalogue",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-catalogue-1" },
            { type = "unlock-recipe", recipe = "highenergy-data-248" },
            { type = "unlock-recipe", recipe = "radioisotop-data-248" },
            { type = "unlock-recipe", recipe = "star-data-248" },
            { type = "unlock-recipe", recipe = "structural-data-248" }
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-1.png",
        icon_size = 128,
        prerequisites = { "utility-science-pack", "fi_robo_tech", "fi_crystal_tech", "fi_solid_reactor_tech", "fi_train_tech",
                          "se-space-radiation-laboratory", "se-space-astrometrics-laboratory", "se-space-electromagnetics-laboratory", "se-space-mechanical-laboratory" },
        unit = {
            count = 100,
            time = 60,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack", 1 },
                { "chemical-science-pack", 1 },
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "production-science-pack", 1 },
                { "utility-science-pack", 1 },
                { "kr-optimization-tech-card", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-catalogue-2",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-catalogue-2" },
            { type = "unlock-recipe", recipe = "fusion-stable-data" },
            { type = "unlock-recipe", recipe = "laser-heating-data" },
            { type = "unlock-recipe", recipe = "magnet-stabilazer-data" },
            { type = "unlock-recipe", recipe = "plasma-rotating-data" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-2.png",
        icon_size = 128,
        prerequisites = { "se-space-particle-collider", "fu_laser_tech", "fu_magnet_tech", "fu_plasma_tech", "fu_fusor_tech" },
        unit = {
            count = 10,
            time = 60,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack", 1 },
                { "chemical-science-pack", 1 },
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "production-science-pack", 1 },
                { "utility-science-pack", 1 },
                { "se-energy-science-pack-1", 1 },
                { "fusion-science-pack-1", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-catalogue-3",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-catalogue-3" },
            { type = "unlock-recipe", recipe = "fusion-speed-data" },
            { type = "unlock-recipe", recipe = "laser-calculation-data" },
            { type = "unlock-recipe", recipe = "magnet-trajectory-data" },
            { type = "unlock-recipe", recipe = "plasma-spinning-data" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-3.png",
        icon_size = 128,
        prerequisites = { "kr-fusion-energy" },
        unit = {
            count = 100,
            time = 60,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack", 1 },
                { "chemical-science-pack", 1 },
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "production-science-pack", 1 },
                { "utility-science-pack", 1 },
                { "se-energy-science-pack-2", 1 },
                { "fusion-science-pack-1", 1 },
                { "fusion-science-pack-2", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-catalogue-4",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-catalogue-4" },
            { type = "unlock-recipe", recipe = "fusion-accuracy-data" },
            { type = "unlock-recipe", recipe = "laser-decay-data" },
            { type = "unlock-recipe", recipe = "magnet-contain-data" },
            { type = "unlock-recipe", recipe = "plasma-star-data" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-catalogue-4.png",
        icon_size = 128,
        prerequisites = { "fu_activator_tech" },
        unit = {
            count = 500,
            time = 60,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack", 1 },
                { "chemical-science-pack", 1 },
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "production-science-pack", 1 },
                { "utility-science-pack", 1 },
                { "se-energy-science-pack-3", 1 },
                { "fusion-science-pack-1", 1 },
                { "fusion-science-pack-2", 1 },
                { "fusion-science-pack-3", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-science-pack",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-science-pack-1" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-science-pack-1.png",
        icon_size = 128,
        prerequisites = { "space-fusion-catalogue" },
        unit = {
            count = 100,
            time = 60,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack", 1 },
                { "chemical-science-pack", 1 },
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "production-science-pack", 1 },
                { "utility-science-pack", 1 },
                { "kr-optimization-tech-card", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-science-pack-2",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-science-pack-2" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-science-pack-2.png",
        icon_size = 128,
        prerequisites = { "space-fusion-catalogue-2" },
        unit = {
            count = 100,
            time = 60,
            ingredients = {
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "fusion-science-pack-1", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-science-pack-3",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-science-pack-3" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-science-pack-3.png",
        icon_size = 128,
        prerequisites = { "space-fusion-catalogue-3" },
        unit = {
            count = 200,
            time = 60,
            ingredients = {
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "fusion-science-pack-1", 1 },
                { "fusion-science-pack-2", 1 },
            },
        },
    },
    {
        type = "technology",
        name = "space-fusion-science-pack-4",
        effects = {
            { type = "unlock-recipe", recipe = "fusion-science-pack-4" },
        },
        icon = "__all-the-overhaul-modpack__/graphics/icons/fusion-science-pack-4.png",
        icon_size = 128,
        prerequisites = { "space-fusion-catalogue-4" },
        unit = {
            count = 500,
            time = 60,
            ingredients = {
                { "se-rocket-science-pack", 1 },
                { "space-science-pack", 1 },
                { "fusion-science-pack-1", 1 },
                { "fusion-science-pack-2", 1 },
                { "fusion-science-pack-3", 1 },
            },
        },
    }
})